[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "CI=false npm run build"
  publish = "build/"
  environment = { REACT_APP_URL = 'https://2022.hackillinois.org' }

[functions]
  directory = "functions"
